---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    name: {{ .Values.deployment.name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
